### PR TITLE
Modify UI for refinements

### LINKED ISSUE #15: UI refinement to region selection
Follow-up to #3!

I noticed that if you just click instead of drag on this screen: 

image

It will still allow you to move forward. I think we need to:

1. set a minimum region size - maybe 10x10 pixels? 
2. display the selection even after you've finished selecting it - once you let go the mouse, it's not clear what you've selected
3. display both A and B selections on the final screen - it kind of seems confusing like the example red boxes were your selections, but that's not the case. Let's just show the actual selections you've made in the final screen, so you know exactly what's happend?

image

This is going really well. Thanks, @Divy123 !

### PR DESCRIPTION
**Pull request by Divy123**
Fixes #15 .

### CODE REVIEW

**Comment by Divy123** [comment]
@jywarren please review.

**Comment by Divy123** [comment]
@jywarren made them red:
https://divy123.github.io/colorimetry/public/

**Comment by Divy123** [comment]
If it looks good, we can merge it here.

**Comment by jywarren** [comment]
Awesome!

**Comment by jywarren** [comment]
Awesome!

**Pull request merged**
